[package]
name = "bliss-audio"
version = "0.2.0"
authors = ["Polochon-street <polochonstreet@gmx.fr>"]
edition = "2018"
license = "GPL-3.0-only"
description = "A song analysis library for making playlists"
homepage = "https://lelele.io/bliss.html"
repository = "https://github.com/Polochon-street/bliss-rs"
keywords = ["audio", "analysis", "MIR", "playlist", "similarity"]
readme = "README.md"

[package.metadata.docs.rs]
features = ["bliss-audio-aubio-rs/rustdoc"]
no-default-features = true

[features]
# Building ffmpeg until either
# https://github.com/zmwangx/rust-ffmpeg/pull/60
# or https://github.com/zmwangx/rust-ffmpeg/pull/62 is in
default = ["bliss-audio-aubio-rs/static", "build-ffmpeg"]
build-ffmpeg = ["ffmpeg-next/build"]
bench = []
python-bindings = ["bliss-audio-aubio-rs/fftw3"]

[dependencies]
ripemd160 = "0.9.0"
ndarray-npy = "0.8.0"
ndarray = { version = "0.15.0", features = ["rayon"] }
num_cpus = "1.13.0"
ndarray-stats = "0.5.0"
rustfft = "5.0.1"
lazy_static = "1.4.0"
rayon = "1.5.0"
crossbeam = "0.8.0"
noisy_float = "0.2.0"
ffmpeg-next = "4.3.8"
log = "0.4.14"
env_logger = "0.8.3"
thiserror = "1.0.24"
# Until https://github.com/aubio/aubio/issues/336 is somehow solved
# Hopefully we'll be able to use the official aubio-rs at some point.
bliss-audio-aubio-rs = "0.2.0"
strum = "0.21"
strum_macros = "0.21"
serde = { version = "1.0", optional = true, features = ["derive"] }
