[package]
name = "bliss-audio-symphonia"
version = "0.6.5"
authors = ["Polochon-street <polochonstreet@gmx.fr>", "NGnius (Graham) <ngniusness@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "A song analysis library for making playlists"
homepage = "https://lelele.io/bliss.html"
repository = "https://github.com/NGnius/bliss-rs"
keywords = ["audio", "analysis", "MIR", "playlist", "similarity"]
readme = "README.md"

[package.metadata.docs.rs]
features = ["bliss-audio-aubio-rs/rustdoc", "library"]
no-default-features = true

[features]
default = ["bliss-audio-aubio-rs/static"]
# Build ffmpeg instead of using the host's.
# Use if you want to build python bindings with maturin.
python-bindings = ["bliss-audio-aubio-rs/fftw3"]
# Enable the benchmarks with `cargo +nightly bench --features=bench`
bench = []
library = [
    "serde", "dep:rusqlite", "dep:dirs", "dep:tempdir",
    "dep:anyhow", "dep:serde_ini", "dep:serde_json",
    "dep:indicatif",
]
serde = ["dep:serde"]

[dependencies]
ripemd160 = "0.9.0"
ndarray-npy = "0.8.0"
ndarray = { version = "0.15.0", features = ["rayon"] }
num_cpus = "1.13.0"
ndarray-stats = "0.5.0"
rustfft = "5.0.1"
lazy_static = "1.4.0"
rayon = "1.5.0"
crossbeam = "0.8.0"
noisy_float = "0.2.0"
symphonia = { version = "0.5", features = ["mp3", "aac", "alac"]}
rubato = { version = "0.12" }
log = "0.4.14"
env_logger = "0.8.3"
thiserror = "1.0.24"
# Until https://github.com/aubio/aubio/issues/336 is somehow solved
# Hopefully we'll be able to use the official aubio-rs at some point.
bliss-audio-aubio-rs = "0.2.0"
strum = "0.21"
strum_macros = "0.21"
rcue = "0.1.1"

# Deps for the library feature
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0.59", optional = true }
serde_ini = { version = "0.2.0", optional = true }
tempdir = { version = "0.3.7", optional = true }
rusqlite = { version = "0.27.0", optional = true }
dirs = { version = "4.0.0", optional = true }
anyhow = { version = "1.0.58", optional = true }
indicatif = { version = "0.17.0", optional = true }

[dev-dependencies]
mime_guess = "2.0.3"
glob = "0.3.0"
anyhow = "1.0.45"
clap = "2.33.3"
pretty_assertions = "1.2.1"
serde_json = "1.0.59"

[[example]]
name = "library"
required-features = ["library"]

[[example]]
name = "library_extra_info"
required-features = ["library"]


[[example]]
name = "playlist"
required-features = ["serde"]
